<div class="post-content flex-container" itemprop="articleBody">
    <form action="results_dog_form.php" method="post">
        <ul class="flex-outer">
            <li>
                <label for="dog_breed">Dog breed</label>
                <select id="dog_breed" name="dog_breed" required>
                    <option value="">Select</option>
                    <option value="Affenpinscher">Affenpinscher</option>
                    <option value="Afghan Hound">Afghan Hound</option>
                    <option value="Airedale Terrier">Airedale Terrier</option>
                    <option value="Akita"> Akita</option>
                    <option value="Alaskan Malamute"> Alaskan Malamute</option>
                    <option value="American English Coonhound"> American English Coonhound</option>
                    <option value="American Eskimo Dog(toy)"> American Eskimo Dog(toy)</option>
                    <option value="American Eskimo Dog (miniature)"> American Eskimo Dog (miniature)</option>
                    <option value="American Eskimo Dogs(standard)"> American Eskimo Dogs(standard)</option>
                    <option value="American Foxhound"> American Foxhound</option>
                    <option value="American Hairless Terrier"> American Hairless Terrier</option>
                    <option value="American Staffordshire Terrier"> American Staffordshire Terrier</option>
                    <option value="Anatolian Shepherd Dog"> Anatolian Shepherd Dog</option>
                    <option value="Australian Cattle Dog"> Australian Cattle Dog</option>
                    <option value="Australian Shepherd"> Australian Shepherd</option>
                    <option value="Australian Terrier"> Australian Terrier</option>
                    <option value="Basenji"> Basenji</option>
                    <option value="Basset Hound"> Basset Hound</option>
                    <option value="Beagles(13 inches & under)"> Beagles(13 inches & under)</option>
                    <option value="Beagles(13-15 inches)"> Beagles(13-15 inches)</option>
                    <option value="Bearded Collie"> Bearded Collie</option>
                    <option value="Beauceron"> Beauceron</option>
                    <option value="Bedlington Terrier"> Bedlington Terrier</option>
                    <option value="Belgian Malinois"> Belgian Malinois</option>
                    <option value="Belgian Sheepdog"> Belgian Sheepdog</option>
                    <option value="Belgian Tervuren"> Belgian Tervuren</option>
                    <option value="Bergamaco"> Bergamaco</option>
                    <option value="Berger Picard"> Berger Picard</option>
                    <option value="Bernese Mountain Dog"> Bernese Mountain Dog</option>
                    <option value="Bichons Frise"> Bichons Frise</option>
                    <option value="Black and Tan Coonhound"> Black and Tan Coonhound</option>
                    <option value="Black Russian Terrier"> Black Russian Terrier</option>
                    <option value="Bloodhound"> Bloodhound</option>
                    <option value="Bluetick Coonhound"> Bluetick Coonhound</option>
                    <option value="Boerboel"> Boerboel</option>
                    <option value="Border Collie"> Border Collie</option>
                    <option value="Border Terrier"> Border Terrier</option>
                    <option value="Borzoi"> Borzoi</option>
                    <option value="Boston Terrier"> Boston Terrier</option>
                    <option value="Bouviers des Flandre"> Bouviers des Flandre</option>
                    <option value="Boxer"> Boxer</option>
                    <option value="Briard"> Briard</option>
                    <option value="Brittany"> Brittany</option>
                    <option value="Brussels Griffon"> Brussels Griffon</option>
                    <option value="Bull Terrier"> Bull Terrier</option>
                    <option value="Bulldog"> Bulldog</option>
                    <option value="Bullmastiff"> Bullmastiff</option>
                    <option value="Cairn Terrier"> Cairn Terrier</option>
                    <option value="Canaan Dog"> Canaan Dog</option>
                    <option value="Cardigan Welsh Corgi"> Cardigan Welsh Corgi</option>
                    <option value="Cavalier King Charles Spaniel"> Cavalier King Charles Spaniel</option>
                    <option value="Cesky Terrier"> Cesky Terrier</option>
                    <option value="Chihuahua"> Chihuahua</option>
                    <option value="Chinese Creted"> Chinese Creted</option>
                    <option value="Chinee SharPei"> Chinee SharPei</option>
                    <option value="Chinook"> Chinook</option>
                    <option value="Chow Chow"> Chow Chow</option>
                    <option value="Cirnechi dell Etna"> Cirnechi dell Etna</option>
                    <option value="Collie"> Collie</option>
                    <option value="Coton de Tulear"> Coton de Tulear</option>
                    <option value="Dachshunds(standard)"> Dachshunds(standard)</option>
                    <option value="Dachshund(miniature)"> Dachshund(miniature)</option>
                    <option value="Dalmatian"> Dalmatian</option>
                    <option value="Dandie Dinmont Terrier"> Dandie Dinmont Terrier</option>
                    <option value="Doberman Pinscher"> Doberman Pinscher</option>
                    <option value="Dogue de Bordeaux"> Dogue de Bordeaux</option>
                    <option value="English Foxhound"> English Foxhound</option>
                    <option value="English Toy Spaniel"> English Toy Spaniel</option>
                    <option value="Entlebucher Mountain Dog"> Entlebucher Mountain Dog</option>
                    <option value="Finnish Lapphund"> Finnish Lapphund</option>
                    <option value="Finnish Spitz"> Finnish Spitz</option>
                    <option value="Fox Terrier (Smooth)"> Fox Terrier (Smooth)</option>
                    <option value="Fox Terrier (Wire)"> Fox Terrier (Wire)</option>
                    <option value="French Bulldog"> French Bulldog</option>
                    <option value="German Pinscher"> German Pinscher</option>
                    <option value="German Shepherd Dog"> German Shepherd Dog</option>
                    <option value="Giant Schnauzer"> Giant Schnauzer</option>
                    <option value="Glen of Imaal Terrier"> Glen of Imaal Terrier</option>
                    <option value="Great Dane"> Great Dane</option>
                    <option value="Great Pyrenese"> Great Pyrenese</option>
                    <option value="Greater Swiss Mountain Dog"> Greater Swiss Mountain Dog</option>
                    <option value="Greyhound"> Greyhound</option>
                    <option value="Harrier"> Harrier</option>
                    <option value="Havanese"> Havanese</option>
                    <option value="Ibizan Hound"> Ibizan Hound</option>
                    <option value="Icelandic Sheepdog"> Icelandic Sheepdog</option>
                    <option value="Irish Terrier"> Irish Terrier</option>
                    <option value="Irish Wolfhound"> Irish Wolfhound</option>
                    <option value="Italian Greyhound"> Italian Greyhound</option>
                    <option value="Japanese Chin"> Japanese Chin</option>
                    <option value="Keehonden"> Keehonden</option>
                    <option value="Kerry Blue Terrier"> Kerry Blue Terrier</option>
                    <option value="Komondorok"> Komondorok</option>
                    <option value="Kuvazok"> Kuvazok</option>
                    <option value="Lagoti Romagnoli"> Lagotti Romagnoli</option>
                    <option value="Lakeland Terrier"> Lakeland Terrier</option>
                    <option value="Leonberger"> Leonberger</option>
                    <option value="Lhasa Apso"> Lhasa Apso</option>
                    <option value="Lowchen"> Lowchen</option>
                    <option value="Maltese"> Maltese</option>
                    <option value="Manchester Terrier(toy)"> Manchester Terrier(toy)</option>
                    <option value="Manchester Terriers (standard)"> Manchester Terriers (standard)</option>
                    <option value="Mastiff"> Mastiff</option>
                    <option value="Miniature American Shepherd"> Miniature American Shepherd</option>
                    <option value="Miniature Bull Terrier"> Miniature Bull Terrier</option>
                    <option value="Miniature Pinscher"> Miniature Pinscher</option>
                    <option value="Miniature Schnauzer"> Miniature Schnauzer</option>
                    <option value="Neapolitan Mastiff"> Neapolitan Mastiff</option>
                    <option value="Newfoundland"> Newfoundland</option>
                    <option value="Norfolk Terrier"> Norfolk Terrier</option>
                    <option value="Norwegian Buhund"> Norwegian Buhund</option>
                    <option value="Norwegian Elkhound"> Norwegian Elkhound</option>
                    <option value="Norwegian Lundehund"> Norwegian Lundehund</option>
                    <option value="Norwich Terrier"> Norwich Terrier</option>
                    <option value="Old English Sheepdog"> Old English Sheepdog</option>
                    <option value="Otterhound"> Otterhound</option>
                    <option value="Papillon"> Papillon</option>
                    <option value="Parson Russell Terrier"> Parson Russell Terrier</option>
                    <option value="Pekingee"> Pekingee</option>
                    <option value="Pembroke Welsh Corgi"> Pembroke Welsh Corgi</option>
                    <option value="Petits Bassets Griffons Vendeen"> Petits Bassets Griffons Vendeen</option>
                    <option value="Pharaoh Hound"> Pharaoh Hound</option>
                    <option value="Plott"> Plott</option>
                    <option value="Pointer"> Pointer</option>
                    <option value="Pointer (German Shorthaired)"> Pointer (German Shorthaired)</option>
                    <option value="Pointer (German Wirehaired)"> Pointer (German Wirehaired)</option>
                    <option value="Polish Lowland Sheepdog"> Polish Lowland Sheepdog</option>
                    <option value="Pomeranian"> Pomeranian</option>
                    <option value="Poodle(toy)"> Poodle(toy)</option>
                    <option value="Poodle (miniature)"> Poodle (miniature)</option>
                    <option value="Poodles(standard)"> Poodles(standard)</option>
                    <option value="Portuguese Podengo Pequeno"> Portuguese Podengo Pequeno</option>
                    <option value="Portuguese Water Dog"> Portuguese Water Dog</option>
                    <option value="Pug"> Pug</option>
                    <option value="Pulik"> Pulik</option>
                    <option value="Pumik"> Pumik</option>
                    <option value="Pyrenean Shepherd"> Pyrenean Shepherd</option>
                    <option value="Rat Terrier"> Rat Terrier</option>
                    <option value="Redbone Coonhound"> Redbone Coonhound</option>
                    <option value="Retrievers (Cheapeake Bay)"> Retrievers (Cheapeake Bay)</option>
                    <option value="Retriever (Curly Coated)"> Retriever (Curly Coated)</option>
                    <option value="Retriever (Flat Coated)"> Retriever (Flat Coated)</option>
                    <option value="Retriever (Golden)"> Retriever (Golden)</option>
                    <option value="Retriever (Labrador)"> Retriever (Labrador)</option>
                    <option value="Retriever (Nova Scotia Duck Tolling)"> Retriever (Nova Scotia Duck Tolling)</option>
                    <option value="Rhodesian Ridgeback"> Rhodesian Ridgeback</option>
                    <option value="Rottweiler"> Rottweiler</option>
                    <option value="Russell Terrier"> Russell Terrier</option>
                    <option value="Saluki"> Saluki</option>
                    <option value="Samoyed"> Samoyed</option>
                    <option value="Schipperke"> Schipperke</option>
                    <option value="Scottish Deerhound"> Scottish Deerhound</option>
                    <option value="Scottish Terrier"> Scottish Terrier</option>
                    <option value="Sealyham Terrier"> Sealyham Terrier</option>
                    <option value="Slightly less Setters (English)"> slightly less Setters (English)</option>
                    <option value="Setter (Gordon)"> Setter (Gordon)</option>
                    <option value="Setters (Irish Red and White)"> Setters (Irish Red and White)</option>
                    <option value="Setters (Irish)"> Setters (Irish)</option>
                    <option value="Shetland Sheepdog"> Shetland Sheepdog</option>
                    <option value="Shiba Inu"> Shiba Inu</option>
                    <option value="Shih Tzu"> Shih Tzu</option>
                    <option value="Siberian Husky"> Siberian Husky</option>
                    <option value="Silky Terrier"> Silky Terrier</option>
                    <option value="Skye Terrier"> Skye Terrier</option>
                    <option value="Sloughi"> Sloughi</option>
                    <option value="Soft Coated Wheaten Terrier"> Soft Coated Wheaten Terrier</option>
                    <option value="Spaniel (American Water)"> Spaniel (American Water)</option>
                    <option value="Spaniel (Boykin)"> Spaniel (Boykin)</option>
                    <option value="Spaniel (Clumber)"> Spaniel (Clumber)</option>
                    <option value="Spaniels (English Cocker)"> Spaniels (English Cocker)</option>
                    <option value="Spaniels (English Springer)"> Spaniels (English Springer)</option>
                    <option value="Spaniel (Field)"> Spaniel (Field)</option>
                    <option value="Spaniels (Irih Water)"> Spaniels (Irish Water)</option>
                    <option value="Spaniels (Susex)"> Spaniels (Susex)</option>
                    <option value="Spaniels (Welh Springer)"> Spaniels (Welsh Springer)</option>
                    <option value="Spanish Water Dog"> Spanish Water Dog</option>
                    <option value="Spinoni Italiani"> Spinoni Italiani</option>
                    <option value="St. Bernard"> St. Bernard</option>
                    <option value="Staffordshire Bull Terrier"> Staffordshire Bull Terrier</option>
                    <option value="Standard Schnauzer"> Standard Schnauzer</option>
                    <option value="Swedish Vallhund"> Swedish Vallhund</option>
                    <option value="Tibetan Mastiff"> Tibetan Mastiff</option>
                    <option value="Tibetan Terrier"> Tibetan Terrier</option>
                    <option value="Tibetan Spaniel"> Tibetan Spaniel</option>
                    <option value="Toy Fox Terrier"> Toy Fox Terrier</option>
                    <option value="Treeing Walker Coonhound"> Treeing Walker Coonhound</option>
                    <option value="Vizsla"> Vizsla</option>
                    <option value="Weimaraner"> Weimaraner</option>
                    <option value="Welsh Terrier"> Welsh Terrier</option>
                    <option value="West Highland White Terrier"> West Highland White Terrier</option>
                    <option value="Whippet"> Whippet</option>
                    <option value="Wirehaired Pointing Griffon"> Wirehaired Pointing Griffon</option>
                    <option value="Wirehaired Vizsla"> Wirehaired Vizsla</option>
                    <option value="Xoloitzcuintli(toy)"> Xoloitzcuintli(toy)</option>
                    <option value="Xoloitzcuintli(miniature)"> Xoloitzcuintli(miniature)</option>
                    <option value="Xoloitzcuintli(standard)"> Xoloitzcuintli(standard)</option>
                    <option value="Yorkshire Terrier"> Yorkshire Terrier</option>

                </select>
            </li>

